Flask_web_app/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note
from .import db
from random import randint
import json
import paho.mqtt.client as mqtt
import time
import rainy

SOTRAGE1 = 'res1.txt'
SOTRAGE2 = 'res2.txt'
SOTRAGE4 = 'res4.txt'

views = Blueprint('views',__name__)

temperature = 0
humidity = 0 
light = 0
light_mode = False

MQTT_SERVER = "mqtt.ohstem.vn"
MQTT_PORT = 1883
MQTT_USERNAME = "Khang"
MQTT_PASSWORD = ""
MQTT_TOPIC_PUB1 = MQTT_USERNAME + "/feeds/V1" #cam bien nhiet do
MQTT_TOPIC_PUB2 = MQTT_USERNAME + "/feeds/V2" #cam bien do am   
MQTT_TOPIC_PUB4 = MQTT_USERNAME + "/feeds/V4" #cam bien anh sang
MQTT_TOPIC_PUB5 = MQTT_USERNAME + "/feeds/V5"
MQTT_TOPIC_PUB6 = MQTT_USERNAME + "/feeds/V6"
MQTT_TOPIC_SUB = MQTT_USERNAME + "/feeds/#"

def mqtt_connected(client, userdata, flags, rc):
    print("Connected succesfully!!")
    client.subscribe(MQTT_TOPIC_SUB)


def mqtt_subscribed(client, userdata, mid, granted_qos):
    print("Subscribed to Topic!!!")

def mqtt_published(client, userdata, mid):
    print("Message published with mid: " + str(mid))

def mqtt_recv_message(client, userdata, message):
    global temperature, humidity, light
    print("In recv_message")
    if message.topic == f"{MQTT_TOPIC_PUB1}":
        temperature = str(message.payload.decode("utf-8"))
    elif message.topic == f"{MQTT_TOPIC_PUB2}":
        humidity = str(message.payload.decode("utf-8"))
    elif message.topic == f"{MQTT_TOPIC_PUB4}":
        light = str(message.payload.decode("utf-8"))
    return temperature, humidity, light


mqttClient = mqtt.Client()
mqttClient.username_pw_set(MQTT_USERNAME, MQTT_PASSWORD)
mqttClient.connect(MQTT_SERVER, int(MQTT_PORT), 60)


# Register mqtt events
mqttClient.on_publish = mqtt_published
mqttClient.on_connect = mqtt_connected
mqttClient.on_subscribe = mqtt_subscribed
mqttClient.on_message= mqtt_recv_message

mqttClient.loop_start()

@views.route('/', methods=['GET','POST'])
@login_required
def home():
    if request.method == 'POST':
        note= request.form.get('note')
        if len(note) < 1:
            flash('Note is too short', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added', category='success')
    return render_template("home.html", user = current_user)

@views.route('/delete-note',methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            
    return jsonify({'success': True})

@views.route('/dashboard',methods=['GET','POST'])
def dashboard():
    return render_template('dashboard.html',user = current_user)

@views.route('/model',methods=['GET','POST'])
def model():
    return render_template('model.html',user = current_user)

@views.route('/dashboardupdate',methods=['GET','POST'])
def get_sensor_reading():
    pressure = 1
    return jsonify({
        'temperature':temperature,
        'humidity':humidity,
        'light':light,
    })

@views.route('/lightupdate',methods=['GET','POST'])
def get_light_button():
    data = request.get_json()
    signal = data['isLightOn']
    if signal == True:
        signal =1
    else:
        signal=0
    mqttClient.publish(MQTT_TOPIC_PUB5, signal)
    print(type(signal))
    return jsonify({
        'signal': signal,
    })
@views.route('/waterupdate',methods=['GET','POST'])
def get_water_button():
    data = request.get_json()
    signal = data['isWaterOn']
    if signal == True:
        signal =1
    else:
        signal=0
    mqttClient.publish(MQTT_TOPIC_PUB6, signal)
    print(type(signal))
    return jsonify({
        'signal': signal,
    })

@views.route('/predict')
def predict_rain():
    rainy_prediction_mm= rainy.predict()
    return jsonify({'rainy_prediction_mm': rainy_prediction_mm})

@views.route('/updatecsv', methods=['POST'])
def update_csv():
    try:
        data = request.json

        # Check if all required keys are present in the received data
        required_keys = ['date', 'province', 'max', 'min', 'rain', 'humidi', 'averageTemp']
        for key in required_keys:
            if key not in data:
                return f"Error: '{key}' is missing from the received data", 400

        # Ensure that numeric values are converted to appropriate types
        data['max'] = float(data['max'])
        data['min'] = float(data['min'])
        data['rain'] = float(data['rain'])
        data['humidi'] = float(data['humidi'])
        data['averageTemp'] = float(data['averageTemp'])
        
        # Append data to CSV file
        with open('hochiminh.csv', 'a') as f:
            f.write(f"{data['date']},{data['province']},{data['max']},{data['min']},{data['rain']},{data['humidi']},{data['averageTemp']}\n")

        return 'Data appended to CSV file successfully.', 200

    except Exception as e:
        return f"Error updating CSV: {str(e)}", 500

Flask_web_app/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <title>{% block title %}Home{% endblock %}</title/>
    
        <style>
            .logo {
                width: 97%;
                height: auto;
                margin: 30px;
            }
            .logotitle {
                text-align: center;
                font-weight: bold;
                font-size: 64px;
                font-family: fantasy;
                word-spacing: 2px;
                letter-spacing: 4px;
                color: #1BBFDA;
                text-shadow: 2px 2px -4px #000000;
                -webkit-text-stroke-width: 0.5px;
                -webkit-text-stroke-color: black;
                text
            }
        </style>
    </head>    
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar"
            >
                <span class= "navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class='navbar-nav'>
                    {% if user.is_authenticated %}
                    <a class= "nav-item nav-link" id="home" href="/">Home</a>
                    <a class= "nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class= "nav-item nav-link" id="login" href="/login">Login</a>
                    <a class= "nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class = "logo">
            <h2 class = "logotitle"> FARMER'S WEATHER TRACKING TOOL</h2>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category =='error' %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type = "button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% else %}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type = "button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        <script
            type="text/javascript" 
            src="{{ url_for('static', filename='index.js') }}"
        ></script>
    </body>
</html>

Flask_web_app/website/templates/dashboard.html
{%extends "base.html" %} {% block title %}Dashboard{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
    body {
        background-image: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(157,232,172,1) 0%, rgba(90,193,82,1) 100%);;
        font-family: Arial, sans-serif;
        box-sizing: border-box;
    }
    .card {
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border: none;
    }

    .card-header {
        background-color: #007bff;
        color: #fff;
        border-radius: 10px 10px 0 0;
        text-align: center;
    }

    .card-body {
        padding: 20px;
        text-align: center;
    }

    .card-title {
        font-size: 1.2rem;
        font-weight: bold;
    }

    .metric-value {
        font-size: 1.2rem;
        font-weight: bold;
    }

    .btn-container {
        text-align: center;
        margin-top: 20px;
    }

    .control-btn {
        margin-right: 10px;
    }

    .fa-lightbulb {
        color: #f39c12;
    }

    .fa-tint {
        color: #3498db;
    }
    .temperature-chart {
        height: 400px; /* Adjust the height as needed */
      }
    #BgTemperature{
        background-image: linear-gradient(to right, #ffecd2 0%, #fcb69f 100%);
        border-radius:  0 0 10px 10px;
    }
    #BgHumidity{
        background-image: linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%);
        border-radius:  0 0 10px 10px;
    }
    #BgLight{
        background-image: radial-gradient( circle 763px at 18.3% 24.1%,  rgba(255,249,137,1) 7.4%, rgba(226,183,40,1) 58.3% );
        border-radius:  0 0 10px 10px;
    }
</style>
<body>
    <div class="container mt-5">
        <div class="row justify-content-around gap-2">
            <div class="col-md-auto" >
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Temperature</h5>
                    </div>
                    <div class="card-body"  id="BgTemperature">
                        <p class="metric-value"><span id="temperature">Loading...</span>°C</p>
                    </div>
                </div>
            </div>
            <div class="col-md-auto">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Rainy Prediction (mm)</h5>
                    </div>
                    <div class="card-body">
                        <p class="metric-value"><span id="rainy-prediction">Loading ...</span> mm</p>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title" >Humidity</h5>
                    </div>
                    <div class="card-body" id="BgHumidity">
                        <p class="metric-value"><span id="humidity">Loading...</span>%</p>
                    </div>
                </div>
            </div>
            
            <div class="col-md-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Light</h5>
                    </div>
                    <div class="card-body" id="BgLight">
                        <p class="metric-value"><span id="light">Loading...</span>%</p>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="btn-container">
            <button class="btn btn-warning control-btn" id="light-control-btn"><i class="fas fa-lightbulb"></i> Turn On Lights</button>
            <button class="btn btn-primary control-btn" id="water-pump-control-btn"><i class="fas fa-tint"></i> Turn On Water Pumps</button>
        </div>
    </div>
    <div class="btn-container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <!-- Canvas for temperature chart -->
                        <canvas id="temperatureChart" class="temperature-chart"></canvas>
                    </div>
                </div>
            </div>
        </div>
</div class="btn-container">
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/epoch/0.8.4/js/epoch.min.js"></script>
<script>
    let temperatureData = [];
    let humidityData = [];
    var rainamount;
    function initializeDashboard() {
        // Call fetchData initially
        const data = fetchData();
        // Set an interval to call fetchData every 5 seconds (adjust as needed)
    }
    // Assume fetchData is defined in an external JavaScript file
    async function fetchData() {
        try {
            const response = await fetch('/dashboardupdate', {
                method: 'POST',
            });
            const data = await response.json();
            // Extract specific values from the data object
            const temperature = data.temperature;
            //const pressure = data.pressure;
            const humidity = data.humidity;
            const light = data.light;
            temperatureData.push(parseFloat(temperature));
            humidityData.push(parseFloat(humidity));
            
            // Update the UI elements with the received data
            document.getElementById('temperature').textContent = temperature;
            //document.getElementById('pressure').textContent = pressure;
            document.getElementById('humidity').textContent = humidity;
            document.getElementById('light').textContent = light;

            console.log(data.temperature)
            // Now you can safely log the temperature

        } catch (error) {
            console.error('Error fetching data:', error);
        }
    }
    setInterval(initializeDashboard, 1000);
    async function updateRainyPrediction() {
        try {
            const response = await fetch('/predict');
            const data = await response.json();
            const rainyPrediction = data.rainy_prediction_mm;
            
            rainamount = rainyPrediction
            // Update the UI element with the received rainy prediction data
            document.getElementById('rainy-prediction').textContent = parseInt(rainyPrediction);

        } catch (error) {
            console.error('Error fetching data:', error);
        }
    }
    // Inside the updateCSV() function or wherever appropriate
    async function updateCSV() {
        try {
            const maxTemperature = Math.max(...temperatureData);
            const minTemperature = Math.min(...temperatureData);
            const avgTemperature = temperatureData.reduce((acc, curr) => acc + curr, 0) / temperatureData.length;
            const avgHumidity = humidityData.reduce((acc, curr) => acc + curr, 0) / humidityData.length;
            const province = 'Ho Chi Minh City';
            console.log(maxTemperature, minTemperature, avgTemperature, avgHumidity, rainamount[0][0])

            const newData = {
                "date": "2024-02-19",
                "province": "Ho Chi Minh City",
                "max": maxTemperature,
                "min": minTemperature,
                "rain": rainamount[0][0],
                "humidi": avgHumidity,
                "averageTemp": avgTemperature,
            };
            
            // Send data to Flask API endpoint for updating CSV file
            const response = await fetch('/updatecsv', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(newData),
                
                
            });
            console.log(response);
            if (response.ok) {
                console.log('Data sent to Flask API successfully.');
                temperatureData = [];
                humidityData = [];
            } else {
                console.error('Failed to send data to Flask API.');
            }
        } catch (error) {
            console.error('Error updating CSV:', error);
        }
    }

    
    // Call updateRainyPrediction initially
    updateRainyPrediction();
    // Set an interval to call updateRainyPrediction every 20 seconds
    setInterval(updateRainyPrediction, 10000); // 20 seconds in milliseconds
        

    updateCSV(); 
    setInterval(updateCSV, 10000);
    // Call fetchData when the page loads
    let isLightOn = false;

    async function getData() {
        const response = await fetch('/lightupdate', {
            method: 'POST',
            headers: {"Content-Type" : "application/json"},
            body: JSON.stringify({ isLightOn: isLightOn })  // Send isLightOn as part of request body
        });
        try {
            const data = await response.json();
            console.log(data);
        } catch (error) {
            console.error('Error:', error);
        }
    }

    document.getElementById('light-control-btn').addEventListener('click', function() {
        isLightOn = !isLightOn;
        getData();  // Call the getData function
        if (isLightOn) {
            document.getElementById('light-control-btn').textContent = 'Turn Off Lights';
            // Code to turn on lights
        } else {
            document.getElementById('light-control-btn').textContent = 'Turn On Lights';
            // Code to turn off lights
        }
    });

    // JavaScript code to toggle the button text and action for water pumps
    let isWaterOn = false;

    async function getData1() {
        const response = await fetch('/waterupdate', {
            method: 'POST',
            headers: {"Content-Type" : "application/json"},
            body: JSON.stringify({ isWaterOn: isWaterOn })  // Send isLightOn as part of request body
        });
        try {
            const data = await response.json();
            console.log(data);
        } catch (error) {
            console.error('Error:', error);
        }
    }

    document.getElementById('water-pump-control-btn').addEventListener('click', function() {
        isWaterOn = !isWaterOn;
        getData1();
        if (isWaterOn) {
            document.getElementById('water-pump-control-btn').textContent = 'Turn Off Water Pumps';
            // Code to turn on water pumps
        } else {
            document.getElementById('water-pump-control-btn').textContent = 'Turn On Water Pumps';
            // Code to turn off water pumps
        }
    });

    document.addEventListener('DOMContentLoaded', function () {
        const temperatureChartCtx = document.getElementById('temperatureChart').getContext('2d');
        const temperatureChart = new Chart(temperatureChartCtx, {
            type: 'line',
            data: {
                labels: [],
                datasets: [{
                    label: 'Temperature',
                    data: [],
                    backgroundColor: 'rgba(255, 99, 132, 0.2)', // Adjust colors as needed
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        // Function to fetch temperature data and update the chart
        async function updateTemperatureChart() {
            try {
                const response = await fetch('/dashboardupdate', {
                    method: 'POST',
                });
                const data = await response.json();
                const temperature = document.getElementById('temperature').textContent;
                const timestamp = new Date().toLocaleTimeString(); // Assuming you want to display time on x-axis

                // Update chart data
                
                // Remove older data if more than 10 data points
                if (temperatureChart.data.labels.length > 10) {
                    temperatureChart.data.labels.shift();
                    temperatureChart.data.datasets[0].data.shift();
                }
                temperatureChart.data.labels.push(timestamp);
                temperatureChart.data.datasets[0].data.push(temperature);
                temperatureChart.update();
                
            } catch (error) {
                console.error('Error fetching data:', error);
            }
        }

        // Update temperature chart every 5 seconds (adjust as needed)
        setInterval(updateTemperatureChart, 2000);
    });
</script>
{% endblock %}

Flask_web_app/website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<style>
.container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
}

.button-container {
    margin-top: 20px;
}

.button-container a {
    margin: 10px;
}

button {
    padding: 15px 30px;
    font-size: 18px;
    border: none;
    background-color: #4CAF50;
    color: white;
    cursor: pointer;
    border-radius: 8px;
}

button:hover {
    background-color: #45a049;
}
</style>

<div class="container">
    <h2>Welcome !</h2>
    <div class="button-container">
        <a href="{{ url_for('views.dashboard') }}"><button>Go to Dashboard</button></a>
        <a href="{{ url_for('views.model') }}"><button>Go to AI prediction</button></a>
    </div>
</div>
{% endblock %}

Flask_web_app/website/templates/login.html
{%extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Flask_web_app/website/templates/sign-up.html
{%extends "base.html" %} {% block title %}Sign Up{% endblock %}
{% block content %}
    <form method="POST">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Enter email"
            />
        </div>
        <div class="form-group">
            <label for="firstname">First Name</label>
            <input
                type="text"
                class="form-control"
                id="firstname"
                name="firstname"
                placeholder="Enter firstname"
            />
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="Enter password"
            />
        </div>
        <div class="form-group">
            <label for="password2">Password Confirm</label>
            <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="Confirm password"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}